### ISSUE TITLE
How to profile executable code in wasmtime-py?

### ISSUE THREAD

**Issue by dbezhetskov** [bytecodealliance/wasmtime-py#130]
Hi, thanks for the python bindings!
I'm instantiating wasm modules with wasmtime-py and want to see generated assembly code for my modules.
Is it possible to get any dump or something?

**Comment by alexcrichton** [comment]
At this time there's not an "official" way to do this but Wasmtime's compiled artifacts are ELF images so what you can do is call `Module.serialize` and then pass the output to `objdump -S` to take a look at the assembly. You can also use the `wasmtime compile` CLI command and run `objdump -S your.cwasm`.

Do you mean though profiling the time-based execution of WebAssembly code? For example via stack sampling in a profiler like Linux's `perf`? If so that's a whole different ballpark and has a different answer.

**Comment by dbezhetskov** [comment]
thansk @alexcrichton , it is what I was looking for

**Comment by dbezhetskov** [comment]
Btw, what are options wasmtime have for `perf` based profiling?

**Comment by alexcrichton** [comment]
While it's [possible](https://docs.wasmtime.dev/examples-profiling-perf.html) it's not easy. The support has limitations such as you have to attach `perf` early before wasmtime does anything which isn't always trivial.

I'm not sure whether the `Config` options are plumbed to enable the jitdump support for perf through these bindings, but if not PRs are of course welcome to add them!

**Comment by dbezhetskov** [comment]
I see, thanks!
