### ISSUE TITLE
beginner tip?

### ISSUE THREAD

**Issue by bbartling** [bytecodealliance/wasmtime-py#201]
Could someone give me a tip on an experiment, in Rust `lib.rs`:

```
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn should_charge_battery(current_price: f32, future_high_price: f32, current_battery_level: f32, battery_capacity: f32) -> bool {
    // Check if the current price is lower than the anticipated high price
    // and if the battery is not already fully charged
    let should_charge = current_price < future_high_price && current_battery_level < battery_capacity;

    // Return true to indicate battery should be charged, else false
    should_charge
}
```

that i compiled with `> wasm-pack build --target web`

And in python my script, I can load the WASM:
```
import wasmtime

def load_wasm_module(wasm_file):
    # Create an engine
    engine = wasmtime.Engine()

    # Read the WASM module binary
    with open(wasm_file, 'rb') as file:
        wasm_bytes = file.read()

    # Compile the module
    return wasmtime.Module(engine, wasm_bytes)

# Specify the path to your WASM file
wasm_file_path = './target/wasm32-unknown-unknown/release/geb_building.wasm'

# Load the WASM module
wasm_module = load_wasm_module(wasm_file_path)
print(wasm_module)
```

But I am stuck after this... any tips appreciated not a lot of wisdom here.. This will print:
`<wasmtime._module.Module object at 0x0000020853340A10>`

Am curious how to interact with the WASM file from Python.

**Comment by alexcrichton** [comment]
Thanks for the report, but there's unfortunately a few conflations going on here. Wasmtime is not compatible with wasm-pack or wasm-bindgen. Both wasm-{pack,bindgen} are intende for the web, not out-of-browser runtimes like Wasmtime.

Otherwise for actually executing WebAssembly there's not a great tutorial for this crate at this time. You can explore the examples and tests but you'll need to additionally learn more context about how Rust is translated to WebAssembly to understand how to interact with Rust-generated modules.

**Comment by bbartling** [comment]
thanks for the response!
