### ISSUE TITLE
how to import wasm env function?

### ISSUE THREAD

**Issue by dengliangjun** [bytecodealliance/wasmtime-py#55]
I use emcc to compile a wasm file.
the wasm file import many external functions, such as "env"."memset", env.memcpy and so on. How can I correctly import those functions. whether there are some base  file or lib that I can directly import them?
I have read examples, no otherelse complex examples.
thanks for your reading. I hope get your help. thanks.

**Comment by alexcrichton** [comment]
Thanks for the report! You may not get a ton of success using emcc output running in Wasmtime though since that's primarily intended to run on the web AFAIK. You can, however, define imported functions using a [`Linker`](https://bytecodealliance.github.io/wasmtime-py/#wasmtime.Linker) to instantiate modules. There's nothing built-in, however, to instantiate modules with, so you'd have to provide a custom implementation of all of these intrinsics.
